$ErrorActionPreference = 'Stop'
# Usage: pwsh -NoProfile -File scripts/third-party-notices.ps1 [build-module-manifest]
# Run after a production build. The manifest includes emitted main and worker chunks.
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$manifestPath = if ($args.Count) { [IO.Path]::GetFullPath($args[0], $projectRoot) } else { Join-Path $projectRoot '.iwsdk/build-modules.json' }
$outputRoot = Join-Path $projectRoot 'public/licenses'
$distRoot = Join-Path $projectRoot 'dist'
if (-not (Test-Path -LiteralPath (Join-Path $distRoot 'index.html') -PathType Leaf)) {
    throw 'Production output is missing; run a production build first.'
}
$statePath = Join-Path $projectRoot '.iwsdk/license-files.json'
$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
if (-not $manifest.modules.Count) { throw 'Build module manifest is empty; run a production build first.' }

$packages = @{}
foreach ($module in $manifest.modules) {
    $modulePath = ($module -split '\?', 2)[0].Replace('\', '/')
    if ($modulePath -notmatch '(^|/)node_modules/') { continue }
    $absolute = [IO.Path]::GetFullPath($modulePath, $projectRoot)
    $relative = [IO.Path]::GetRelativePath($projectRoot, $absolute)
    if ($relative.StartsWith('..') -or [IO.Path]::IsPathRooted($relative)) {
        throw 'Build module points outside this project.'
    }
    $directory = [IO.Path]::GetDirectoryName($absolute)
    while ($directory -and $directory -ne $projectRoot) {
        $packagePath = Join-Path $directory 'package.json'
        if (Test-Path -LiteralPath $packagePath -PathType Leaf) {
            $package = Get-Content -LiteralPath $packagePath -Raw -Encoding UTF8 | ConvertFrom-Json
            if ($package.name -and $package.version) {
                if ($package.name -eq '@drawcall/uikitml') { throw 'Unlicensed UIKitML parser remains in the production build.' }
                $packages[$directory] = $package
                break
            }
        }
        $directory = [IO.Path]::GetDirectoryName($directory)
    }
    if (-not $packages.ContainsKey($directory)) { throw "Cannot identify npm package for module: $module" }
}
if (-not $packages.Count) { throw 'No shipped npm packages were identified.' }

# Prepare every copy before modifying output, and fail rather than invent missing terms.
$copies = [Collections.Generic.List[object]]::new()
$index = [Collections.Generic.List[string]]::new()
$index.Add('Between Hands - Third-party notices')
$index.Add('')
$index.Add('Generated by scripts/third-party-notices.ps1 from emitted production modules, including workers.')
$index.Add('These notices cover packages present in that build; development-only dependencies are not included.')
$index.Add('License files below are copied verbatim from installed npm packages or the pinned upstream sources listed below. Their terms remain applicable.')
$index.Add('The bundled Inter font is covered by the complete @pmndrs/msdfonts LICENSE, including the SIL Open Font License 1.1.')
$index.Add('')
$plannedFiles = @{}
foreach ($entry in ($packages.GetEnumerator() | Sort-Object { $_.Value.name }, { $_.Value.version })) {
    $package = $entry.Value
    $packageRoot = $entry.Key
    $licenseFiles = @(Get-ChildItem -LiteralPath $packageRoot -File | Where-Object {
        $_.Name -match '^(LICENSE|LICENCE|NOTICE|COPYING|OFL)([.\-_].*)?$'
    })
    foreach ($subdirectory in @('licenses', 'LICENSES')) {
        $subpath = Join-Path $packageRoot $subdirectory
        if (Test-Path -LiteralPath $subpath -PathType Container) {
            $licenseFiles += @(Get-ChildItem -LiteralPath $subpath -Recurse -File)
        }
    }
    $licenseFiles = @($licenseFiles | Sort-Object FullName -Unique)
    $upstreamSource = $null
    if (-not $licenseFiles.Count -and $package.name -eq 'yoga-layout' -and $package.version -eq '3.2.1') {
        $packageRoot = Join-Path $PSScriptRoot 'license-sources/yoga-layout-3.2.1'
        $upstreamSource = Get-Content -LiteralPath (Join-Path $packageRoot 'source.json') -Raw -Encoding UTF8 | ConvertFrom-Json
        $licenseFiles = @(Get-Item -LiteralPath (Join-Path $packageRoot 'LICENSE'))
        if ((Get-FileHash -LiteralPath $licenseFiles[0].FullName -Algorithm SHA256).Hash -ne $upstreamSource.sha256) {
            throw 'Pinned upstream Yoga license does not match its provenance hash.'
        }
    }
    if (-not $licenseFiles.Count) { throw "No full license text found for shipped package $($package.name)@$($package.version)." }
    $folder = ($package.name -replace '^@', '' -replace '/', '__') + '@' + $package.version
    $index.Add("$($package.name) $($package.version)")
    $index.Add("Declared license: $($package.license ?? 'See retained license text')")
    if ($upstreamSource) { $index.Add("Source: $($upstreamSource.source)") }
    foreach ($file in $licenseFiles) {
        if ($file.Length -eq 0) { throw "Empty license file in $($package.name)." }
        $localName = [IO.Path]::GetRelativePath($packageRoot, $file.FullName).Replace('\', '/')
        $outputName = "$folder/$localName"
        $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash
        if ($plannedFiles.ContainsKey($outputName)) {
            if ($plannedFiles[$outputName] -ne $hash) { throw "Conflicting license texts for $($package.name)@$($package.version)." }
            continue
        }
        $plannedFiles[$outputName] = $hash
        $copies.Add([pscustomobject]@{ Source = $file.FullName; Relative = $outputName; Hash = $hash })
        $index.Add("  licenses/$outputName")
        $index.Add("  SHA256: $hash")
    }
    $index.Add('')
}

$fontPackages = @($packages.GetEnumerator() | Where-Object { $_.Value.name -eq '@pmndrs/msdfonts' })
$interModules = @($manifest.modules | Where-Object { $_ -match '[/\\]@pmndrs[/\\]msdfonts[/\\].*[/\\]inter\.' })
if ($interModules.Count) {
    if (-not $fontPackages.Count) { throw 'Inter font has no identified license package.' }
    $fontLicense = Get-Content -LiteralPath (Join-Path $fontPackages[0].Key 'LICENSE') -Raw -Encoding UTF8
    if ($fontLicense -notmatch 'Inter Project Authors' -or $fontLicense -notmatch 'SIL OPEN FONT LICENSE Version 1\.1') {
        throw 'Installed Inter notice is missing the expected copyright or full OFL text.'
    }
}

New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null
foreach ($copy in $copies) {
    $target = Join-Path $outputRoot $copy.Relative
    New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($target)) -Force | Out-Null
    Copy-Item -LiteralPath $copy.Source -Destination $target -Force
    if ((Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash -ne $copy.Hash) { throw 'License copy verification failed.' }
    $distTarget = Join-Path $distRoot "licenses/$($copy.Relative)"
    New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($distTarget)) -Force | Out-Null
    Copy-Item -LiteralPath $copy.Source -Destination $distTarget -Force
    if ((Get-FileHash -LiteralPath $distTarget -Algorithm SHA256).Hash -ne $copy.Hash) { throw 'Published license copy verification failed.' }
}

# Remove only files that this script recorded on an earlier run, within public/licenses.
if (Test-Path -LiteralPath $statePath -PathType Leaf) {
    $previous = Get-Content -LiteralPath $statePath -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($old in $previous.files) {
        if ($plannedFiles.ContainsKey($old)) { continue }
        $target = [IO.Path]::GetFullPath($old, $outputRoot)
        $relative = [IO.Path]::GetRelativePath($outputRoot, $target)
        if ($relative.StartsWith('..') -or [IO.Path]::IsPathRooted($relative) -or $target -eq $outputRoot) {
            throw 'Refusing to remove a license outside the generated license directory.'
        }
        if (Test-Path -LiteralPath $target -PathType Leaf) { Remove-Item -LiteralPath $target }
        $distTarget = Join-Path $distRoot "licenses/$relative"
        if (Test-Path -LiteralPath $distTarget -PathType Leaf) { Remove-Item -LiteralPath $distTarget }
    }
}
$index | Set-Content -LiteralPath (Join-Path $projectRoot 'public/THIRD-PARTY-NOTICES.txt') -Encoding UTF8
Copy-Item -LiteralPath (Join-Path $projectRoot 'public/THIRD-PARTY-NOTICES.txt') -Destination (Join-Path $distRoot 'THIRD-PARTY-NOTICES.txt') -Force
New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($statePath)) -Force | Out-Null
@{ files = @($copies.Relative) } | ConvertTo-Json -Depth 3 | Set-Content -LiteralPath $statePath -Encoding UTF8
Write-Output "Collected $($copies.Count) full notice files for $($packages.Count) shipped npm packages."
